POST localhost:8080/api/login
Content-Type: application/json

{
  "account": "admin",
  "password": "admin"
}

### success
GET http://localhost:8080/api/admin/graph
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoic3FXZiIsInVpZCI6IjAxSkZNTjBOQkNYVDVGVkQ5WDk5Mk5WODdUIiwiaWF0IjoxNzM1NTIzODgzLCJleHAiOjE3MzU2MTAyODN9.BSC2lq4m-GcZoBVDBxh9kAmBrVW_uFpBUq0Fkxcko9A

###
POST localhost:8080/api/admin/news
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiIwMUpGTU4wTkJDWFQ1RlZEOVg5OTJOVjg3VCIsInJvbGUiOiJzcVdmIiwiaWF0IjoxNzM1NjExNDQ2LCJleHAiOjE3MzU2OTc4NDZ9.DL2yHyty-NhZIPT2H00xeyEu3qCDxZhhE9e_cA3GHkM

{
  "author": "111",
  "content": "222",
  "title": "333"
}