POST localhost:8080/api/login
Content-Type: application/json

{
  "account": "admin",
  "password": "123456"
}

### success
GET http://localhost:8080/api/admin/graph
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoic3FXZiIsInVpZCI6IjAxSkZNTjBOQkNYVDVGVkQ5WDk5Mk5WODdUIiwiaWF0IjoxNzM1NTIzODgzLCJleHAiOjE3MzU2MTAyODN9.BSC2lq4m-GcZoBVDBxh9kAmBrVW_uFpBUq0Fkxcko9A


### success 获取全部用户
GET localhost:8080/api/admin/users
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoic3FXZiIsInVpZCI6IjAxSkZNTjBOQkNYVDVGVkQ5WDk5Mk5WODdUIiwiaWF0IjoxNzM1NzE0NzYwLCJleHAiOjE3MzU4MDExNjB9.B6JQrKN4mLHpAEDT6YPzqbPHEqtYvLl7dC3s4voiyZA
### success 基于账号重置密码
PUT localhost:8080/api/admin/users/2022222998/password
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoic3FXZiIsInVpZCI6IjAxSkZNTjBOQkNYVDVGVkQ5WDk5Mk5WODdUIiwiaWF0IjoxNzM1ODc2Mzg3LCJleHAiOjE3MzU5NjI3ODd9.xUMmvV_61seMCTJHi6qsTayNqNby2IhVfT0NH7cfIs0


### success 基于账号重置密码
PUT localhost:8080/api/admin/users/20222328/password
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoic3FXZiIsInVpZCI6IjAxSkZNTjBOQkNYVDVGVkQ5WDk5Mk5WODdUIiwiaWF0IjoxNzM1ODc2Mzg3LCJleHAiOjE3MzU5NjI3ODd9.xUMmvV_61seMCTJHi6qsTayNqNby2IhVfT0NH7cfIs0
### success 添加实验室
POST localhost:8080/api/admin/lab
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoic3FXZiIsInVpZCI6IjAxSkZNTjBOQkNYVDVGVkQ5WDk5Mk5WODdUIiwiaWF0IjoxNzM1NzE0NzYwLCJleHAiOjE3MzU4MDExNjB9.B6JQrKN4mLHpAEDT6YPzqbPHEqtYvLl7dC3s4voiyZA
Content-Type: application/json

{
  "name": "test",
  "manager": "11",
  "description": "22",
  "quantity": "25",
  "state": "1"
}
### success 添加用户
POST localhost:8080/api/admin/user
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoic3FXZiIsInVpZCI6IjAxSkZNTjBOQkNYVDVGVkQ5WDk5Mk5WODdUIiwiaWF0IjoxNzM1ODc3MTA5LCJleHAiOjE3MzU5NjM1MDl9.FsId3ra8Z0UqW1yUh7v2fopQgcWiQ25-RrZbByqH8lY
Content-Type: application/json

{
  "password": "12",
  "telephone": "34",
  "name": "sy",
  "role": "wewe",
  "account": "20222328"
}