POST localhost:8080/api/login
Content-Type: application/json

{
  "account": "account04",
  "password": "123456"
}

### admin
POST localhost:8080/api/login
Content-Type: application/json

{
"account": "admin",
"password": "123456"
}

###
POST localhost:8080/api/login
Content-Type: application/json

{
  "account": "account05",
  "password": "123456"
}