GET localhost:8080/api/users/news
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoid2V3ZSIsInVpZCI6IjAxSkZKQUZDUVBKNFY1NjIxTkhUVlNZV01FIiwiaWF0IjoxNzM1NTY0MjU2LCJleHAiOjE3MzU2NTA2NTZ9.qu7WkWs6YzBatuFWWHFp1YYua9-bvaVftGzH9FvjXUk