GET localhost:8080/api/users/news
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoid2V3ZSIsInVpZCI6IjAxSkZKQUZDUVBKNFY1NjIxTkhUVlNZV01FIiwiaWF0IjoxNzM1NTY0MjU2LCJleHAiOjE3MzU2NTA2NTZ9.qu7WkWs6YzBatuFWWHFp1YYua9-bvaVftGzH9FvjXUk


### success 查询所有实验室
GET localhost:8080/api/users/labs
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoid2V3ZSIsInVpZCI6IjAxSkZKQUZDUVBKNFY1NjIxTkhUVlNZV01FIiwiaWF0IjoxNzM1NzI5NjUwLCJleHAiOjE3MzU4MTYwNTB9.BkDvvbNNipXIpWC6liAqZzTVcvaYK_g-vHT82gagtEg

### success 修改密码
PATCH localhost:8080/api/users/password
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI1Iiwicm9sZSI6Indld2UiLCJpYXQiOjE3MzU4MjA2NTMsImV4cCI6MTczNTkwNzA1M30.-uYH7IQiDnPuKts33Yrto6IKJ_RPTojPhdplClfJo6w
Content-Type: application/json

{
  "password": "123456"
}

### success 查询指定老师指定学期的课表
GET localhost:8080/api/users/coursetable/24-1
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2Iiwicm9sZSI6Indld2UiLCJpYXQiOjE3MzU3MzI0MTEsImV4cCI6MTczNTgxODgxMX0.2KciBL2GgFabge_-plhudlvwlkHt1N4YKyzYmzL5A-I

### success 获取老师的全部课程信息
GET http://localhost:8080/api/users/courses
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoid2V3ZSIsInVpZCI6IjUiLCJpYXQiOjE3MzU4MjU2ODcsImV4cCI6MTczNTkxMjA4N30.YMGkpOKeDjrkDabdk4nLR_cqnGlRBAVg74dMI6qYQw0
### success 更新课程
PATCH http://localhost:8080/api/users/course
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoic3FXZiIsInVpZCI6IjIiLCJpYXQiOjE3MzU3MzAzMTMsImV4cCI6MTczNTgxNjcxM30.NJuZjYLzB7janbuV-rY_H-74CnC7BaSqWnINTSaNOVo
Content-Type: application/json

{
  "id": "1",
  "name": "高等数学",
  "quantity": 120,
  "semester": "24-1",
  "clazz": "数学与应用数学",
  "type": 1,
  "teacherId": "01JFJ5CWY6FD4XTTHR42FBS6A4",
  "experimentHour": 8
}

###  success 添加课程
POST http://localhost:8080/api/users/course
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoic3FXZiIsInVpZCI6IjIiLCJpYXQiOjE3MzU3MzAzMTMsImV4cCI6MTczNTgxNjcxM30.NJuZjYLzB7janbuV-rY_H-74CnC7BaSqWnINTSaNOVo
Content-Type: application/json

{
  "name": "离散数学",
  "quantity": 120,
  "semester": "24-1",
  "clazz": "数学与应用数学",
  "type": 1,
  "teacherId": "01JFJ5CWY6FD4XTTHR42FBS6A4",
  "experimentHour": 8
}

### success 预约
POST localhost:8080/api/users/appointment
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoic3FXZiIsInVpZCI6IjIiLCJpYXQiOjE3MzU3MzAzMTMsImV4cCI6MTczNTgxNjcxM30.NJuZjYLzB7janbuV-rY_H-74CnC7BaSqWnINTSaNOVo
Content-Type: application/json

{
  "course": "2",
  "dayofweek": "2",
  "labId": "901",
  "labName": "901",
  "semester": "24-1",
  "nature": "临时",
  "section": "1",
  "week": "8",
  "teacher": "2"
}

### success 删除预约
DELETE localhost:8080/api/users/appointment
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoic3FXZiIsInVpZCI6IjIiLCJpYXQiOjE3MzU3MzAzMTMsImV4cCI6MTczNTgxNjcxM30.NJuZjYLzB7janbuV-rY_H-74CnC7BaSqWnINTSaNOVo
Content-Type: application/json

{
  "id": "7"
}

### success 删除预约
DELETE localhost:8080/api/users/appointment
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoic3FXZiIsInVpZCI6IjIiLCJpYXQiOjE3MzU3MzAzMTMsImV4cCI6MTczNTgxNjcxM30.NJuZjYLzB7janbuV-rY_H-74CnC7BaSqWnINTSaNOVo
Content-Type: application/json

{
  "id": "3",
  "course": "2",
  "teacher": "2"
}


### success 基于实验室id，查预约表
GET localhost:8080/api/users/appointments/901
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoic3FXZiIsInVpZCI6IjIiLCJpYXQiOjE3MzU3MzAzMTMsImV4cCI6MTczNTgxNjcxM30.NJuZjYLzB7janbuV-rY_H-74CnC7BaSqWnINTSaNOVo

### success 基于老师id,课程id，获取人数可用和不可用的实验室
GET localhost:8080/api/users/labs/2
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoic3FXZiIsInVpZCI6IjIiLCJpYXQiOjE3MzU3MzAzMTMsImV4cCI6MTczNTgxNjcxM30.NJuZjYLzB7janbuV-rY_H-74CnC7BaSqWnINTSaNOVo


### 删除指定老师指定id对应的课程,要判断是否有预约记录
DELETE localhost:8080/api/users/courses/course/01JGKASTA7QXF8JE3GZ67HM3YQ
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoid2V3ZSIsInVpZCI6IjgiLCJpYXQiOjE3MzU4MjU5MDEsImV4cCI6MTczNTkxMjMwMX0.hFrmKg47o6rDnqfnV9LfUhHeitliKrKwX38Y3LLSVBQ
### 删除指定老师指定ids对应的课程,要判断是否有预约记录
DELETE localhost:8080/api/users/courses/3,5
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoic3FXZiIsInVpZCI6IjIiLCJpYXQiOjE3MzU3MzAzMTMsImV4cCI6MTczNTgxNjcxM30.NJuZjYLzB7janbuV-rY_H-74CnC7BaSqWnINTSaNOVo
